# This workflow will build a Java project with Maven
# For more information see: https://aberger.at/blog/2021/05/29/cloud-startproject.html

name: Build Application

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DISTRIBUTION_FOLDER: target/distribution-0.0.1-dist/docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - uses: actions/checkout@v2

    - name: cache maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-build-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-m2-

    - name: build with Maven
      run: |
        mvn -Dquarkus-profile=prod -Dbase.href="/" -B package

    - name: build docker images
      run: |
        ./build.sh build ${{ env.REGISTRY }}/${{ github.repository }}
        docker image ls
      working-directory: distribution/${{ env.DISTRIBUTION_FOLDER }}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.TOKEN }}

    - name: push docker images
      run: ./build.sh push ${{ env.REGISTRY }}/${{ github.repository }}
      working-directory: distribution/${{ env.DISTRIBUTION_FOLDER }}

    - name: install ssh key
      uses: caberger/install-ssh-key@v1.0
      with:
        ssh-private-key:  ${{ secrets.SSH_SERVER_PRIVATE_KEY }}
        user: ${{ secrets.SERVER_USER }}
        server: ${{ secrets.SERVER }}
        alias: server

    - name: install on server
      working-directory: distribution
      run: |
        pwd
        ls -l
        ssh server "rm -rf ~/dist && mkdir -p ~/dist"
        scp install.sh server:~/dist
        scp ${{ env.DISTRIBUTION_FOLDER }}/docker-compose-production.yml server:~/dist/docker-compose.yml
        ssh server "chmod +x ~/dist/install.sh"
        ssh server "cd ~/dist && sudo ./install.sh ${{ github.actor }} ${{ github.TOKEN }} ${{ env.REGISTRY }}/${{ github.repository }} ${{ secrets.SERVER_USER }}"
        ssh server "sudo mkdir -p /usr/local/bin/application"
        ssh server "sudo mv /home/${{ secrets.SERVER_USER }}/dist/docker-compose.yml /usr/local/bin/application"
